# 东方财富 - session
eastmoney:
  validatekey: 2fc312a2-2730-59fa-a71a-6daf309390f0
  cookie: st_si=7845973208075; st_asi=delete; b-user-id=5gfv23hw-d31c-3f53-99ce-e660u3jhgwe102de; st_pvi=69309129852821043795; st_sp=2025-05-01%2001%3A25%3A07; st_inirUrl=https%3A%2F%2Fwww.eastmoney.com%2F; st_sn=01; st_psi=202505011000005345-11234501-282323; Yybdm=9527; Uid=XV%8dfe213safYqI7hg33522dDJSew%3D%3D; mobileimei=bda537db-b638-5d73-735ac913915f; Uuid=db7eb9edsd7603210ddfksd03093362097ad2



# 通达信-根目录
tdx-path: "C:/soft/new_tdx"



# Mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tdx?useSSL=false&serverTimezone=Asia/Shanghai&character_set_server=utf8mb4&useUnicode=true&characterEncoding=UTF-8&socketTimeout=150000&connectTimeout=30000
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 指定连接池类型

    druid:
      # 基础连接池参数
      initial-size: 10
      min-idle: 10
      max-active: 300
      max-wait: 60000  # 获取连接超时时间（毫秒）

      # 连接存活检测
      time-between-eviction-runs-millis: 60000  # 检测间隔
      min-evictable-idle-time-millis: 300000  # 最小空闲时间
      test-while-idle: true  # 空闲时检测连接有效性
      validation-query: SELECT 1  # 检测SQL

      # 监控与防火墙
      filters: stat,wall,slf4j  # 启用统计、SQL防火墙、日志
      filter:
        stat:
          slow-sql-millis: 2000  # 慢SQL阈值（2秒）
          log-slow-sql: true
        wall:
          enabled: true  # 启用SQL注入防御

      # 监控页面配置
      stat-view-servlet:
        enabled: true  # 启用监控页面
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true  # 统计Web请求
        url-pattern: /*
        exclusions: "*.js,*.css,/druid/*"

